### ISSUE TITLE
Provide a CLI for converting without electron dependency

### ISSUE THREAD

**Issue by LoveIsGrief** [jgraph/drawio#1533]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

I'm creating graphs for documentation on [readthedocs.io](https://readthedocs.org/) using your wonderful tool and have them committed to my project. Right now, I have to manually export to `.png` and `.html` (for use within an iframe) and commit them.

**Describe the solution you'd like**

I would like to only commit the `.drawio` file, convert it to all the formats I need in the CI, and do so reasonably quickly without having to download electron. An npm, pip or single binary would be great.

**Describe alternatives you've considered**

readthedocs.io supports using a custom docker image, so I could create one with the AppImage in it and call it. I'm not sure if it can run headless withou XvFB though.

**Additional context**

I thought [mxgraph-js](https://github.com/jgraph/mxgraph-js) would be what I needed, but the repo is archived and I have no idea how to use the library to convert files. It doesn't seem to be a nodejs lib.

**Comment by davidjgraph** [comment]
Any of:

- https://github.com/olberger/docker-drawio-desktop-linux
- https://github.com/rlespinasse/drawio-cli
- https://github.com/rlespinasse/drawio-export

work?

**Comment by LoveIsGrief** [comment]
Hi,

Those solution all wrap the desktop/electron app and are >100MB. That's massive for a CLI application and still doesn't work on CI services, who use their own docker images with their own dependencies. 

Most CIs have pip or npm installed. Would it be a lot of work to provide a `npm install -g drawio-cli` that doesn't have external dependencies like electron and xvfb? 

I was assuming mxgraph-js could be used for this since conversion shouldn't need a DOM, right? Or is it only for use in browsers?

**Comment by davidjgraph** [comment]
mxgraph-js needs a DOM. The project started in 2005, node wasn't a thing...

**Comment by LoveIsGrief** [comment]
I see... are there any plans at all to make it node compatible? Is there any way I could help doing so? The project is archived but still seems to get updates but there's no message as to why, hence the question.
If there are no plans for node or a non-electron CLI then this issue can be voided.

**Comment by helmo** [comment]
Yes it works with Xvfb.
We first tried https://github.com/Burnett01/actions-drawio but when that fail we smashed something together.

Here's what we came up with as a GitHub Action. The cli lines can obviously also be used directly in other scripts.
```
name: Render network diagrams
  
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'diagram.xml'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - run: wget --quiet https://github.com/jgraph/drawio-desktop/releases/download/v14.1.8/draw.io-amd64-14.1.8.deb
    - run: sudo apt install --yes libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libuuid1 libappindicator3-1 libsecret-1-0 xvfb
    - run: sudo dpkg -i draw.io-amd64-14.1.8.deb
    - run: xvfb-run drawio --export --format pdf diagrams.xml
    - run: xvfb-run drawio --export --format png diagrams.xml

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v1
      with:
        name: pdf
        path: diagrams.pdf
    - name: Upload PNG as artifact
      uses: actions/upload-artifact@v1
      with:
        name: png
        path: diagrams.png
```
