### ISSUE TITLE
URL link is not properly generated when doing File-->Export to-->URL. Currently this link opens file in editor even if lightbox tick is chosen on URL creation dialog. Need to manually edit generated URL by adding lightbox=1&

### ISSUE THREAD

**Issue by rootnoir** [jgraph/drawio#1855]
Seems to me, the problem is in this section..
https://github.com/jgraph/drawio/blob/ff20bcd476b55b37a9f705e83e0db39aa6847e8e/src/main/webapp/js/diagramly/EditorUi.js#L5156
IMHO, if (lightbox) will return "params.push('lightbox=1')" every time, when True.. not only when "urlParams['dev'] == '1'"

**Comment by alderg** [comment]
This works as expected, it uses viewer.diagrams.net (where lightbox=1 is implicit).

**Comment by davidjgraph** [comment]
I think the issue is when self-hosted.

**Comment by rootnoir** [comment]
> This works as expected, it uses viewer.diagrams.net (where lightbox=1 is implicit).

ok, how can i get the same in docker-drawio?..
i need a viewer.diagrams.net functional, but self-hosted )

**Comment by rootnoir** [comment]
If it'll be usefull for someone, i've made a solution for docker-drawio in Kubernetes.

**Common part:** you need add ***window.DRAWIO_VIEWER_URL*** and ***window.DRAWIO_LIGHTBOX_URL*** in your ***PreConfig.js***
and viever dns name will **not** be the same as editor dns name (ex. editor: diagrams.local, viever: viewer.diagrams.local)

Just add additional record in DNS for *viewer.diagrams.local* linked to the *diagrams.local*

For Kubernetes edit configmap and ingress:
```
# cat cm2.yaml 
apiVersion: v1
data:
  PreConfig.js: "window.EXPORT_URL = '/export';\nwindow.DRAWIO_VIEWER_URL = 'https://viewer.diagrams.local';\nwindow.DRAWIO_LIGHTBOX_URL = 'https://viewer.diagrams.local';\nwindow.DRAW_MATH_URL = 'math';\nwindow.DRAWIO_CONFIG = null;\nwindow.DRAWIO_GITLAB_URL = 'https://git.local/';\nwindow.DRAWIO_GITLAB_ID = 'ENTER_GITLAB_ID_THERE';\n"
kind: ConfigMap
metadata:
  annotations:
  name: drawio-configs
  namespace: drawio

# cat ing2.yaml 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing-drawio
  namespace: drawio
spec:
  rules:
  - host: diagrams.local
    http:
      paths:
      - backend:
          serviceName: drawio
          servicePort: 8080
        path: /
  - host: viewer.diagrams.local
    http:
      paths:
      - backend:
          serviceName: drawio
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - diagrams.local
    - viewer.diagrams.local
    secretName: default-server-secret
```
