### ISSUE TITLE
DRAWIO_LIGHTBOX_URL config not working when self-hosted

### ISSUE THREAD

**Issue by chookrib** [jgraph/drawio#3175]
### Preflight Checklist

* [ √ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ √ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I am using v20.5.3 self-hosted in domain like http://diagram.explame.com
When set DRAWIO_LIGHTBOX_URL value 'http://diagram.explame.com', the website will not working.

**To Reproduce**
1. Set window.DRAWIO_LIGHTBOX_URL = 'http://diagram.explame.com'; in preConfig.js
2. Open website http://diagram.explame.com
3. The website show error, see screenshots.
4. Remove config DRAWIO_LIGHTBOX_URL, website work correct. but Publish\Link... generate link with https://viewer.diagrams.net/.

**Expected behavior**
Set DRAWIO_LIGHTBOX_URL let Publish\Link... can generate with specified url.

**Screenshots**
![2022-11-11_163731](https://user-images.githubusercontent.com/4644955/201300288-8785e485-6d13-490c-ad3a-09444a03d352.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- v20.5.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 107.0.5304.89

**Additional context**
I read #2149 #750 #2149 #2057, doesn't help solve the problem.

**Comment by davidjgraph** [comment]
Can you test again with the latest build?

**Comment by chookrib** [comment]
test with 20.6.0 and 20.6.2，same problem.

**Comment by jeffshead** [comment]
**AlmaLinux 8.7, Portainer, Niginx Proxy Manager, Drawio v20.7.4**
I'm experiencing the same issue.

```
version: '3.5'
services:
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    environment:
      - DRAWIO_BASE_URL=https://dio.example.com
      - DRAWIO_VIEWER_URL=https://dio.example.com/js/viewer.min.js
      - DRAWIO_LIGHTBOX_URL=https://dio.example.com
    ports:
      - "127.0.0.1:8013:8080"
      - "127.0.0.1:8414:8443"

networks:
  default:
    name: default
    external: true
```
