### ISSUE TITLE
Unable to be authenticated by gitlab

### ISSUE THREAD

**Issue by Ch4mpa9ne** [jgraph/drawio#3404]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I don't use the nginx proxy, the oauth2 authentication by selecting gitlab for the storage is successful to show check page, however if you click Authorize, it will jump to 500. But when I go through the nginx proxy, gitlab always reports an error:
An error has occurred
The authorization server does not support this response type.
Below is my entire nginx configuration file
```

server {
    listen 80;
    server_name drawio.com;

    location / {
        return 302 https://$server_name$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name drawio.com;

    ssl_certificate /etc/certificate/a.crt;
    ssl_certificate_key /etc/certificate/a.key;

    location / {
        proxy_pass https://1x.xx.xx.xx:28081;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Preserve OAuth2 and GitLab authentication parameters
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header X-Requested-With $http_x_requested_with;
        proxy_set_header Accept $http_accept;
    }
}
```

**To Reproduce**
1. Go to main page
2. Click on Save diagrams to GitLab
3. Scroll down to 'Create a Blank Diagram'

**Expected behavior**
Successfully use gitlab for storage

**Screenshots**

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/22672207/222748164-18cd2ee1-64ef-470f-989d-fad5016ef7aa.png">

<img width="932" alt="image" src="https://user-images.githubusercontent.com/22672207/222730431-4cde774c-f50c-4b14-8c61-94ec7320253e.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.0.2 release

**Desktop (please complete the following information):**
 - Browser chrome

**Additional context**
The Request URL between pass nginx or not is:

https://gitlab.com/oauth/authorize?client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&scope=api%20read_repository%20write_repository&redirect_uri=https%3A%2F%2Fdrawio.com%2Fgitlab.html&response_type=token&state=123

https://gitlab.com/oauth/authorize?client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&scope=api%20read_repository%20write_repository&redirect_uri=https%3A%2F%2Fserver.com:8080%2Fgitlab.html&response_type=code&state=cId%3Dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%26domain%3Dcom%26token%3D1tkgd9ukh0usl2iiksv2007jes4dfc7h2s87gdpc46hr3dv5510

And I use docker-compose to deploy it.

```yml
version: '3.6'
services:
  drawio:
    image: jgraph/drawio
    restart: always
    volumes:
      - ./ca-certificates/:/usr/local/share/ca-certificates/:ro
    ports:
      - '1x.xx.xx.xx:28080:8080'
      - '1x.xx.xx.xx:28081:8443'
    environment:
      - DRAWIO_BASE_URL=https://drawio.com
      - DRAWIO_GITLAB_URL=https://gitlab.com
      - DRAWIO_GITLAB_ID=xxxx
      - DRAWIO_GITLAB_SECRET="xxxx"
```
