### ISSUE TITLE
Storing files on server

### ISSUE THREAD

**Issue by p6002** [jgraph/drawio#3611]
Is it possible to add to the compose file to have drawio save the diagrams directly to the server?
For example: `/docker/drawio/diagrams:/something`

```yml
version: "3"

services:
  draw:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    ports:
      - "8553:8080"
      - "8443:8443"
#    environment:
#      PUBLIC_DNS: domain
#      ORGANISATION_UNIT: unit
#      ORGANISATION: org
#      CITY: city
#      STATE: state
#      COUNTRY_CODE: country
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
#      interval: 1m30s
#      timeout: 10s
#      retries: 5
#      start_period: 10s
```
